name: 'instagram_business'
version: '1.1.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]
vars:
  instagram_business:
    media_history_staging: "{{ source('instagram_business', 'media_history') }}"
    media_insights_staging: "{{ source('instagram_business', 'media_insights') }}"
    user_history_staging: "{{ source('instagram_business', 'user_history') }}"
models:
  instagram_business:
    +schema: instagram_business
    +materialized: table
    staging:
      +schema: stg_instagram_business
      +materialized: table
      tmp:
        +materialized: view
