name: 'instagram_business_integration_tests'
version: '1.0.0'
profile: 'integration_tests'
config-version: 2
vars:
  instagram_business:
    instagram_business_media_history_identifier: "instagram_business_media_history_data"
    instagram_business_media_insights_identifier: "instagram_business_media_insights_data"
    instagram_business_user_history_identifier: "instagram_business_user_history_data"
    instagram_business_schema: instagram_business_integration_tests_1
seeds:
  +docs:
    show: false
  instagram_business_integration_tests:
    instagram_business_media_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        user_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        carousel_album_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    instagram_business_media_insights_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
    instagram_business_user_history_data:
      +column_types:
        id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
        ig_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"

models:
  +schema: "instagram_business_{{ var('directed_schema','dev') }}"